### ISSUE TITLE
请问大神，我可以随意使用你的库？

### ISSUE THREAD

**Issue by lindexi** [MengYunfan/Qiniu.uwp#1]
大神你好，看到你也有做图床，
我也有做一个图床：https://github.com/lindexi/Imageshack

我的好多功能没做，想抄袭你的，不知你同意不

**Comment by MengYunfan** [comment]
肯定欢迎啊！后续会提供Nuget版本和上架商店SampleApp

**Comment by lindexi** [comment]
多谢，我有做个图床的app   https://www.microsoft.com/store/apps/9nblggh562r2
